<?php

namespace AppBundle\Repository;

/**
 * DeprRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeprRepository extends \Doctrine\ORM\EntityRepository
{
}
